Repository CosmicMind/Material, pull requests merged in 2018-10, with the labels that each got.

#1167 Fixed tab bar class was not set in some cases
  Sources/iOS/BottomNavigationController.swift
Labels: fix, material

#1115 Introducing Theming to Material
  Material.xcodeproj/project.pbxproj
  Sources/iOS/BaseIconLayerButton.swift
  Sources/iOS/BottomNavigationController.swift
  Sources/iOS/Button.swift
  Sources/iOS/CheckButton.swift
  Sources/iOS/Editor.swift
  Sources/iOS/ErrorTextField.swift
  Sources/iOS/FABButton.swift
  Sources/iOS/FlatButton.swift
  Sources/iOS/IconButton.swift
  Sources/iOS/Material+UIColor.swift
  Sources/iOS/NavigationBar.swift
  Sources/iOS/RaisedButton.swift
  Sources/iOS/StatusBarController.swift
  Sources/iOS/Switch.swift
  Sources/iOS/TabBar.swift
  Sources/iOS/TabsController.swift
  Sources/iOS/TextField.swift
  Sources/iOS/TextView.swift
  Sources/iOS/Theme.swift
  Sources/iOS/Toolbar.swift
  Sources/iOS/ViewController.swift
Labels: material

#1173 Added dialogs
  Material.xcodeproj/project.pbxproj
  Sources/iOS/Button.swift
  Sources/iOS/Dialog.swift
  Sources/iOS/DialogController.swift
  Sources/iOS/DialogView.swift
Labels: high priority, investigate, material

#1174 Added disabling theming globally and per-class
  Sources/iOS/NavigationBar.swift
  Sources/iOS/Theme.swift
Labels: fix, high priority, material

#1180 Manually invalidate NSKeyValueObservation to prevent iOS 10 crash
  Sources/iOS/Editor.swift
  Sources/iOS/Toolbar.swift
Labels: enhancement, fix, high priority, material

#1183 Global font and navigationItem.backButton issue
  Sources/iOS/Button.swift
  Sources/iOS/DialogView.swift
  Sources/iOS/Editor.swift
  Sources/iOS/ErrorTextField.swift
  Sources/iOS/FABMenu.swift
  Sources/iOS/Font.swift
  Sources/iOS/NavigationController.swift
  Sources/iOS/SearchBar.swift
  Sources/iOS/Snackbar.swift
  Sources/iOS/TextField.swift
  Sources/iOS/TextView.swift
  Sources/iOS/Theme.swift
  Sources/iOS/Toolbar.swift
  Sources/iOS/ViewController.swift
Labels: enhancement, feature request, high priority, material
