Repository CosmicMind/Material, pull requests merged in 2018-06, with the labels that each got.

#1080 Fixed license badge href
  README.md
Labels: fix, material

#1046 added ShouldOpen and ShouldClose delegate methods to FABMenuDelegate
  Sources/iOS/FABMenu.swift
Labels: enhancement, material

#1082 Added ErrorTextField validation
  Material.xcodeproj/project.pbxproj
  Sources/iOS/ErrorTextField.swift
  Sources/iOS/ErrorTextFieldValidator.swift
  Sources/iOS/TextField.swift
Labels: enhancement, in progress, material

#1052 Add option to enable/disable dim on rootViewController
  Sources/iOS/NavigationDrawerController.swift
Labels: enhancement, feature request, material

#1101 - Enum for support iPhoneX
  Sources/iOS/Device.swift
Labels: enhancement, material

#1106 Added ability to show visibility and clear button at the same time
  Sources/iOS/TextField.swift
Labels: enhancement, feature request, material
