Repository CosmicMind/Material, pull requests merged in 2018-09, with the labels that each got.

#1147 Support extensions
  Sources/iOS/Application.swift
Labels: fix, material

#1151 New features
  Sources/iOS/BottomNavigationController.swift
  Sources/iOS/Depth.swift
  Sources/iOS/HeightPreset.swift
  Sources/iOS/Material+CALayer.swift
  Sources/iOS/Material+UIView.swift
Labels: enhancement, feature request, high priority, material

#1165 [WIP] Adding interactive swipe
  Sources/iOS/BottomNavigationController.swift
  Sources/iOS/TabBar.swift
  Sources/iOS/TabsController.swift
  Sources/iOS/TransitionController.swift
Labels: enhancement, feature request, high priority, in progress, material
