Repository CosmicMind/Material, pull requests merged in 2018-11, with the labels that each got.

#1185 Reworked layout system
  Material.xcodeproj/project.pbxproj
  Sources/iOS/ErrorTextField.swift
  Sources/iOS/Layout.swift
  Sources/iOS/LayoutAnchor.swift
  Sources/iOS/LayoutAttribute.swift
  Sources/iOS/LayoutConstraint.swift
Labels: enhancement, feature request, material

#1186 Fixed SnackBar laid out incorrectly
  Sources/iOS/SnackbarController.swift
Labels: enhancement, fix, material

#1188 Ignore Carthage checkouts folder
  .gitignore
Labels: enhancement, material
