Repository CosmicMind/Material, pull requests merged in 2019-04, with the labels that each got.

#1214 Fixed status bar visibility and style was not controlled by rootViewController
  Sources/iOS/Table/TableViewController.swift
  Sources/iOS/Transition/TransitionController.swift
Labels: fix, material

#1212 Add basic SwiftPM manifest file
  Package.swift
  README.md
Labels: enhancement, material

#1221 Made Switch more customizable
  Sources/iOS/Switch/Switch.swift
Labels: enhancement, feature request, material

#1222 Removed BottomNavigationController tab bar item title adjustment
  Sources/iOS/BottomTabBar/BottomNavigationController.swift
Labels: enhancement, fix, material
