Repository CosmicMind/Material, pull requests merged in 2019-09, with the labels that each got.

#1263 Update README.md
  README.md
Labels: clean up, material

#1270 Fix to Swift Package Manager missing argument
  Package.swift
  Sources/iOS/Type/Shape.swift
Labels: fix, material

#1269 Fix Crash in Xcode 11
  Sources/iOS/Navigation/NavigationBar.swift
Labels: fix, investigate, material
